"use client";

import { Download } from "lucide-react";
import { AnalysisResult } from "@/lib/types";

interface DownloadButtonProps {
  result: AnalysisResult;
  language: string;
}

function buildMarkdown(result: AnalysisResult, language: string): string {
  const date = new Date().toLocaleString();
  const list = (items: string[]) => items.map((i) => `- ${i}`).join("\n");

  return `# Code Review Report

**Language:** ${language}
**Score:** ${result.overallScore}/100
**Generated:** ${date}

---

## Summary

${result.summary}

---

## Code Quality

${list(result.codeQuality)}

---

## Security Warnings

${list(result.securityWarnings)}

---

## Improvements

${list(result.improvements)}

---

## Recommendations

${list(result.recommendations)}

---

*Generated by CodeReviewAI — Powered by Llama 3.3 70B via Groq*
`;
}

export function DownloadButton({ result, language }: DownloadButtonProps) {
  const handleDownload = () => {
    const md = buildMarkdown(result, language);
    const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `code-review-${language.toLowerCase()}-${Date.now()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <button
      onClick={handleDownload}
      className="flex items-center gap-1.5 px-2.5 py-1 text-xs text-white/35 hover:text-white/60 border border-white/8 hover:border-white/20 rounded transition-all"
    >
      <Download className="h-3 w-3" />
      Export
    </button>
  );
}
